name: DevOps CI Pipeline

# Kapan robot ini harus bekerja?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Apa tugas (jobs) yang harus dikerjakan?
jobs:
  test-and-build:
    name: 🛠️ Uji Kode & Docker
    runs-on: ubuntu-latest # Komputer virtual yang disediakan gratis oleh GitHub

    steps:
      # 1. Robot mengunduh kodemu dari repositori
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      # 2. Robot menyiapkan environment Node.js versi 18
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Robot mencoba menginstal dependency (memastikan package.json aman)
      - name: 📦 Install Dependencies
        run: npm install

        # 🧪 SISIPKAN STEP INI
      - name: 🧪 Run Automated API Tests
        run: npm test
        env:
          NODE_ENV: test

      # 4. Robot melakukan simulasi build Docker image (memastikan Dockerfile aman)
      - name: 🐳 Test Docker Build
        run: docker build -t devops-app-test .